import {useEffect,useState,lazy,Suspense} from 'react';
import {ArrowUpRight,ArrowLeft,ArrowRight,ShoppingBag,UserRound,Menu as MenuIcon,X,Flame,Plus,Heart,Leaf,MapPin,Clock,MessageCircle,Send,VolumeX} from 'lucide-react';
import {api,money} from './lib/api';
import type {Item,CartLine,User} from './types';
import {Modal,Auth,ItemDetails,Cart,Reservation,Account} from './components/Commerce';
const Admin=lazy(()=>import('./components/Admin'));
const photo=(id:string)=>'https://images.unsplash.com/'+id+'?auto=format&fit=crop&w=1600&q=85';
export default function App(){
 const [route,setRoute]=useState(location.hash.slice(1)||'home');const [menu,setMenu]=useState<Item[]>([]);const [config,setConfig]=useState<any>(null);const [user,setUser]=useState<User|null>(null);const [error,setError]=useState('');const [mobile,setMobile]=useState(false);const [modal,setModal]=useState('');const [selected,setSelected]=useState<Item|null>(null);const [toast,setToast]=useState('');
 const [cart,setCart]=useState<CartLine[]>(()=>{try{const data=JSON.parse(localStorage.getItem('ember-cart')||'[]');return Array.isArray(data)&&data.every(l=>typeof l.itemId==='string'&&Number.isInteger(l.quantity)&&l.quantity>0&&l.quantity<=20&&Array.isArray(l.optionIds)&&typeof l.notes==='string')?data:[];}catch{return [];}});
 const [search,setSearch]=useState('');const [category,setCategory]=useState('All');const [veg,setVeg]=useState(false);const [maxPrice,setMaxPrice]=useState(1000);const [favoriteIds,setFavoriteIds]=useState<string[]>([]);
 const [chat,setChat]=useState(false);const [messages,setMessages]=useState<{role:string;text:string}[]>([{role:'assistant',text:'Welcome to the table. Ask about our menu, opening hours or your order.'}]);const [question,setQuestion]=useState('');const [typing,setTyping]=useState(false);
 const notify=(s:string)=>setToast(s);
 async function refresh(){try{const [m,c,u]=await Promise.all([api<Item[]>('/menu'),api('/config'),api<User|null>('/auth/me')]);setMenu(m);setConfig(c);setUser(u);setError('');if(u){const account=await api('/account');setFavoriteIds(account.favorites.map((f:any)=>f.itemId));}}catch(e:any){setError(e.message);}}
 useEffect(()=>{void refresh();const h=()=>{setRoute(location.hash.slice(1)||'home');setMobile(false);window.scrollTo({top:0,behavior:'smooth'});};window.addEventListener('hashchange',h);return()=>window.removeEventListener('hashchange',h);},[]);
 useEffect(()=>{localStorage.setItem('ember-cart',JSON.stringify(cart));},[cart]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),4500);return()=>clearTimeout(t);},[toast]);
 useEffect(()=>{document.title=(route==='home'?'Food with soul':route.split('?')[0].replace(/^./,c=>c.toUpperCase()))+' | Ember & Table';},[route]);
 function add(item:Item,quantity=1,optionIds:string[]=[],notes=''){setCart(old=>{const match=old.findIndex(l=>l.itemId===item.id&&JSON.stringify(l.optionIds)===JSON.stringify(optionIds)&&l.notes===notes);return match<0?[...old,{itemId:item.id,quantity,optionIds,notes}]:old.map((l,i)=>i===match?{...l,quantity:Math.min(20,l.quantity+quantity)}:l);});notify(item.name+' added to your bag');}
 async function favorite(item:Item){if(!user){setModal('auth');return;}try{const result=await api('/favorites/'+item.id,'POST',{});setFavoriteIds(old=>result.favorite?[...old,item.id]:old.filter(id=>id!==item.id));notify(result.favorite?'Saved to favorites':'Removed from favorites');}catch(e:any){notify(e.message);}}
 const book=()=>setModal(user?'reservation':'auth');
 async function ask(text:string){if(!text.trim()||typing)return;setQuestion('');setMessages(old=>[...old,{role:'user',text}]);setTyping(true);try{const result=await api('/chat','POST',{message:text});setMessages(old=>[...old,{role:'assistant',text:result.message}]);}catch(e:any){setMessages(old=>[...old,{role:'assistant',text:e.message}]);}finally{setTyping(false);}}
 const visible=menu.filter(i=>(category==='All'||i.category===category)&&(!veg||i.veg)&&i.price<=maxPrice*100&&(i.name+' '+i.description).toLowerCase().includes(search.toLowerCase()));
 const card=(item:Item)=><article className="food-card" key={item.id}><button className="food-image" onClick={()=>setSelected(item)} aria-label={'Customize '+item.name}><img loading="lazy" src={item.image} alt={item.name}/>{item.featured&&<span className="tag">Chef's pick</span>}</button><button className={'favorite icon '+(favoriteIds.includes(item.id)?'saved':'')} aria-label={'Favorite '+item.name} onClick={()=>favorite(item)}><Heart size={18}/></button><div className="food-content"><div className="eyebrow"><span className={item.veg?'veg-dot':'nonveg-dot'}/>{item.category} <span>• {item.prepMinutes} min</span></div><button className="text-button" onClick={()=>setSelected(item)}><h3>{item.name}</h3></button><p>{item.description}</p><div className="food-bottom"><strong>{money(item.price)}</strong><button className="icon add" disabled={!item.available} onClick={()=>setSelected(item)} aria-label={'Add '+item.name}>{item.available?<Plus size={20}/>:'Sold out'}</button></div></div></article>;
 return <><a className="skip" href="#main" onClick={e=>{e.preventDefault();document.getElementById("main")?.focus();}}>Skip to content</a><div className="announcement">{config?.demo?'DEMO RESTAURANT · NO REAL CHARGES':'SEASONAL INGREDIENTS. SLOW FOOD. GOOD COMPANY.'}<span>Open daily · 12 pm - 11 pm IST</span></div><header><a className="brand" href="#home"><Flame size={29}/><span>ember<span className="brand-small">& TABLE</span></span></a><nav className={mobile?'open':''} aria-label="Main navigation">{['home','menu','about','gallery','contact'].map(link=><a key={link} href={'#'+link} className={route===link?'active':''}>{link==='home'?'Home':link[0].toUpperCase()+link.slice(1)}</a>)}<button onClick={book}>Reservations</button></nav><div className="nav-actions"><button className="icon" aria-label="My account" onClick={()=>user?location.hash='account':setModal('auth')}><UserRound size={20}/></button><button className="icon bag" aria-label="Shopping bag" onClick={()=>setModal('cart')}><ShoppingBag size={20}/><small>{cart.reduce((a,l)=>a+l.quantity,0)}</small></button><a className="button primary nav-order" href="#menu">Order online <ArrowUpRight size={16}/></a><button className="icon mobile-toggle" aria-label="Toggle navigation" aria-expanded={mobile} onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<MenuIcon/>}</button></div></header>
 <main id="main" tabIndex={-1}>{error?<section className="empty"><h1>The kitchen is reconnecting.</h1><p>{error}</p><button className="button" onClick={refresh}>Try again</button><p className="muted">For local setup, start PostgreSQL, seed the database and run both servers.</p></section>:!config?<section className="skeleton" aria-label="Loading restaurant"/>:<>
 {route==='home'&&<><Hero items={menu.filter(i=>i.featured).slice(0,4)} onSelect={setSelected} book={book}/><div className="trust-strip"><span><Leaf size={18}/>Seasonal & thoughtfully sourced</span><span><Flame size={18}/>Made fresh, never rushed</span><span><ShoppingBag size={18}/>From our kitchen to your door</span></div><section className="section"><div className="section-heading"><div><span className="eyebrow">THE GOOD STUFF</span><h2>Come hungry.<br/><em>Leave happy.</em></h2></div><div><p>A few favorites from our kitchen.<br/>Honest ingredients. Extraordinary flavor.</p><a className="text-link" href="#menu">Explore the menu <ArrowUpRight size={18}/></a></div></div><div className="food-grid">{menu.filter(i=>i.featured).slice(0,4).map(card)}</div></section><section className="offer"><Flame size={42}/><div><span className="eyebrow">A LITTLE SOMETHING ON US</span><h2>Your next gathering, with 10% off.</h2><p>Use EMBER10 on orders over ₹500. Up to ₹150 off, subject to availability.</p></div><a className="button cream" href="#menu">Find your favorite <ArrowUpRight size={18}/></a></section><Story/><section className="section reservation-banner"><div><span className="eyebrow">MAKE AN EVENING OF IT</span><h2>Good food tastes better<br/><em>with good company.</em></h2><p>A quiet dinner for two or a long-overdue catch-up.<br/>There's a place for you at our table.</p><button className="button primary" onClick={book}>Book a table <ArrowUpRight size={18}/></button></div><img loading="lazy" src={photo('photo-1517248135467-4c7edcad34c4')} alt="Warm dining room with wooden tables"/></section></>}
 {(route==='menu'||route==='order')&&<section className="section menu-page"><span className="eyebrow">FRESH FROM OUR KITCHEN</span><h1>Find your <em>new favorite.</em></h1><p>Thoughtfully made. Generously served. Customize every bite.</p><div className="menu-toolbar"><label className="search"><span className="sr-only">Search menu</span><input type="search" placeholder="Search a dish or ingredient..." value={search} onChange={e=>setSearch(e.target.value)}/></label><label className="check"><input type="checkbox" checked={veg} onChange={e=>setVeg(e.target.checked)}/> Vegetarian only</label><label>Under ₹{maxPrice}<input aria-label="Maximum price" type="range" min="150" max="1000" step="50" value={maxPrice} onChange={e=>setMaxPrice(+e.target.value)}/></label></div><div className="categories">{['All',...new Set(menu.map(i=>i.category))].map(c=><button key={c} aria-pressed={c===category} className={c===category?'selected':''} onClick={()=>setCategory(c)}>{c}</button>)}</div><p className="muted">{visible.length} dishes · Prices in INR · Allergy information in dish details</p><div className="food-grid">{visible.map(card)}</div>{!visible.length&&<div className="empty"><h3>No dishes match those filters.</h3><button className="button" onClick={()=>{setSearch('');setVeg(false);setMaxPrice(1000);setCategory('All');}}>Reset filters</button></div>}</section>}
 {route==='about'&&<><Story/><section className="section"><h2>Food with a point of view.</h2><div className="values"><article><Leaf/><h3>Seasonal by nature</h3><p>Our demo menu celebrates vegetables, bright herbs and thoughtfully balanced plates.</p></article><article><Flame/><h3>Fire at the heart</h3><p>From blistered pizza to charred paneer, simple techniques let good ingredients shine.</p></article><article><Heart/><h3>Everyone at the table</h3><p>Clear allergens and flexible options help you choose. Speak to the team about dietary requirements.</p></article></div><p className="muted">Ember & Table is a fictional demonstration brand. Replace this story with the client's own history before launch.</p></section></>}
 {route==='gallery'&&<section className="section"><span className="eyebrow">A TASTE OF THE ATMOSPHERE</span><h1>Little moments.<br/><em>Lasting memories.</em></h1><div className="gallery">{menu.slice(0,8).map(i=><button key={i.id} onClick={()=>setSelected(i)} aria-label={'Preview '+i.name}><img loading="lazy" src={i.image} alt={i.name}/><span>{i.name}</span></button>)}</div></section>}
 {route==='contact'&&<Contact config={config} notify={notify}/>}
 {route==='account'&&(user?<Account user={user} menu={menu} notify={notify} onSelect={setSelected} logout={async()=>{await api('/auth/logout','POST',{});setUser(null);setFavoriteIds([]);location.hash='home';}}/>:<section className="empty"><h1>Your seat at the table.</h1><button className="button primary" onClick={()=>setModal('auth')}>Sign in</button></section>)}
 {route==='admin'&&<Suspense fallback={<div className="skeleton"/>}><Admin user={user} menu={menu} config={config} refresh={refresh} notify={notify}/></Suspense>}
 {route.startsWith('reset')&&<section className="section narrow"><Auth initial="reset" onSuccess={u=>{setUser(u);location.hash='account';}} notify={notify}/></section>}
 {['privacy','terms','refund'].includes(route)&&<section className="section narrow"><h1>{route==='privacy'?'Privacy':route==='terms'?'Terms of use':'Refunds & cancellations'}</h1><p className="notice">Demo policy template. Restaurant-specific legal review is required before launch.</p><p>{route==='privacy'?'We store account details, delivery addresses, order history and reservations to provide the service. Card details are collected by the payment provider, not our server. Do not submit real personal data to a public demo. Contact the restaurant to request access or deletion.':route==='terms'?'Prices and availability are confirmed by the server at checkout. Reservations last 90 minutes. All booking times are India Standard Time. The demo venue address, menu and prices are illustrative.':'Unpaid orders can be cancelled before preparation. Online refunds require staff review and are processed by the original payment provider. Cancel reservations at least two hours ahead; contact the team for later changes. Actual refund timelines depend on the provider.'}</p></section>}
 {!['home','menu','order','about','gallery','contact','account','admin','privacy','terms','refund'].includes(route)&&!route.startsWith('reset')&&<section className="empty"><h1>That table isn't here.</h1><a className="button" href="#home">Back home</a></section>}
 </>}</main><footer><div className="footer-grid"><div><a className="brand" href="#home"><Flame/><span>ember<span className="brand-small">& TABLE</span></span></a><p>A little fire. A lot of soul.<br/>Made for the moments that matter.</p><span className="muted">Fictional restaurant · Demo platform</span></div><div><h4>At your table</h4><a href="#menu">Our menu</a><a href="#menu">Order online</a><button onClick={book}>Reservations</button><a href="#about">Our story</a></div><div><h4>Find us</h4><p>{config?.restaurant.address}<br/>{config?.restaurant.hours}</p><a href="#contact">Contact & directions</a><a href="#account">My account</a>{user&&['ADMIN','MANAGER','STAFF'].includes(user.role)&&<a href="#admin">Restaurant dashboard</a>}</div><div><h4>A little inspiration, served fresh.</h4><p>Seasonal specials and news from our kitchen.</p><form onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;try{await api('/newsletter','POST',{email:new FormData(form).get('email')});notify('You are subscribed.');form.reset();}catch(e:any){notify(e.message);}}}><label className="sr-only" htmlFor="newsletter">Email address</label><div className="newsletter"><input id="newsletter" name="email" type="email" required placeholder="Your email address"/><button aria-label="Subscribe"><ArrowRight size={20}/></button></div></form></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Ember & Table. Made with intention.</span><div><a href="#privacy">Privacy</a><a href="#terms">Terms</a><a href="#refund">Refund policy</a></div></div></footer>
 <button className="chat-launch" onClick={()=>setChat(!chat)} aria-label="Open restaurant concierge" aria-expanded={chat}>{chat?<X/>:<MessageCircle/>}<span>Ask Ember</span></button>{chat&&<aside className="chat-window" aria-label="Restaurant concierge"><div className="chat-title"><Flame/><div><strong>Your table concierge</strong><small>{config?.ai||'Demo concierge'} · Menu-grounded answers</small></div><button className="icon" aria-label="Clear conversation" onClick={()=>setMessages([])}><X size={16}/></button></div><div className="chat-messages" aria-live="polite">{messages.map((m,i)=><p key={i} className={m.role}>{m.text}</p>)}{typing&&<p>Checking the menu...</p>}</div><div className="suggestions">{['Vegetarian meal','Show desserts','Opening hours','Track my order'].map(q=><button key={q} disabled={typing} onClick={()=>ask(q)}>{q}</button>)}</div><form onSubmit={e=>{e.preventDefault();void ask(question);}}><input aria-label="Your question" value={question} maxLength={1000} onChange={e=>setQuestion(e.target.value)} placeholder="What sounds good today?"/><button disabled={typing} aria-label="Send message"><Send size={19}/></button></form></aside>}
 {toast&&<div role="status" className="toast">{toast}</div>}
 {modal&&<Modal title={modal==='auth'?'Welcome to the table':modal==='cart'?'Your bag':'Book a table'} onClose={()=>setModal('')}>{modal==='auth'?<Auth notify={notify} onSuccess={u=>{setUser(u);setModal('');notify('Welcome, '+u.name);void refresh();}}/>:modal==='reservation'?<Reservation user={user!} notify={notify} onDone={()=>{setModal('');location.hash='account';}}/>:<Cart cart={cart} setCart={setCart} menu={menu} config={config} user={user} signIn={()=>setModal('auth')} notify={notify} onDone={()=>{setModal('');location.hash='account';}}/>}</Modal>}
 {selected&&<Modal title={selected.name} onClose={()=>setSelected(null)}><ItemDetails item={selected} add={(...args)=>{add(...args);setSelected(null);}} favorite={()=>favorite(selected)}/></Modal>}
 </>;
}
function Hero({items,onSelect,book}:{items:Item[];onSelect:(i:Item)=>void;book:()=>void}){
 const [active,setActive]=useState(0);const [motion,setMotion]=useState(!window.matchMedia('(prefers-reduced-motion: reduce)').matches);const video=import.meta.env.VITE_HERO_VIDEO;
 useEffect(()=>{if(!motion||items.length<2)return;const timer=setInterval(()=>setActive(a=>(a+1)%items.length),6000);return()=>clearInterval(timer);},[motion,items.length]);
 const themes=['#404c30','#653e2c','#3d4a43','#563847'];const item=items[active];
 return <section className={'hero '+(!motion?'paused':'')} style={{backgroundColor:themes[active%4]}}>{video&&motion?<video className="hero-video" autoPlay muted loop playsInline preload="metadata" poster={items[0]?.image}><source src={video} type="video/mp4"/></video>:<div className="cinematic-bg"/>}<div className="hero-grain"/><div className="hero-topline"><span>SEASONAL KITCHEN & NEIGHBORHOOD TABLE</span><span>MUMBAI · EST. DEMO</span></div><div className="hero-copy"><span className="eyebrow"><span className="live-dot"/> GOOD FOOD. GREAT COMPANY.</span><h1>A little fire.<br/>A lot of <em>soul.</em></h1><p>Wood-fired favorites, bold flavors, and a warm<br className="desktop"/> welcome. Pull up a chair. We'll take it from here.</p><div className="hero-buttons"><a className="button cream" href="#menu">Explore our menu <ArrowUpRight size={18}/></a><button className="button outline" onClick={book}>Book a table</button></div><div className="hero-note"><span className="small-line"/> FRESHLY MADE. ALWAYS WORTH IT.</div></div><div className="food-stage" aria-roledescription="carousel" aria-label="Featured dishes"><div className="orbital orbital-one"/><div className="orbital orbital-two"/><span className="ghost-word">SAVOR</span>{items.map((i,index)=>{const position=(index-active+items.length)%items.length;return <button key={i.id} className={'hero-plate plate-'+position} tabIndex={position===0?0:-1} aria-hidden={position!==0} aria-label={'Customize '+i.name} onClick={()=>onSelect(i)}><img src={i.image} alt={position===0?i.name:''} fetchPriority={position===0?'high':'auto'}/></button>;})}<span className="floating-herb herb-one">✦</span><span className="floating-herb herb-two">✧</span><div className="dish-label"><span className="eyebrow">STRAIGHT FROM THE FIRE</span><h3>{item?.name}</h3><span>{item&&money(item.price)} <span className="subtle">/ made to order</span></span></div></div><div className="hero-bottom"><span>01 / THE EMBER EXPERIENCE</span><div className="carousel-controls"><button className="icon" aria-label="Previous dish" disabled={!items.length} onClick={()=>setActive(a=>(a+items.length-1)%items.length)}><ArrowLeft size={19}/></button><span>0{active+1} <span className="subtle">/ 0{items.length}</span></span><button className="icon" aria-label="Next dish" disabled={!items.length} onClick={()=>setActive(a=>(a+1)%items.length)}><ArrowRight size={19}/></button><button className="motion-toggle" aria-pressed={!motion} onClick={()=>setMotion(!motion)}>{motion?'Pause motion':'Play motion'}</button></div><span className="sound-note"><VolumeX size={14}/> A LITTLE ESCAPE, EVERY DAY</span></div></section>;
}
function Story(){return <section className="section story"><div className="story-image"><img loading="lazy" src={photo('photo-1559339352-11d035aa65de')} alt="Sunlit outdoor restaurant seating"/><span>ROOTED IN FLAVOR.<br/>MADE WITH HEART.</span></div><div><span className="eyebrow">OUR KIND OF HOSPITALITY</span><h2>Not just a meal.<br/><em>A feeling.</em></h2><p>There's something about gathering around a table. The first bite, the familiar faces, the conversations that run a little longer than planned.</p><p>That's what Ember & Table is about. Seasonal ingredients, a touch of fire, and food that brings people together.</p><a className="text-link" href="#about">A seat in our story <ArrowUpRight size={18}/></a></div></section>;}
function Contact({config,notify}:{config:any;notify:(s:string)=>void}){const r=config.restaurant;const key=import.meta.env.VITE_GOOGLE_MAPS_KEY;return <section className="section"><span className="eyebrow">COME ON OVER</span><h1>Find your way<br/><em>to our table.</em></h1><div className="contact-grid"><div><h3><MapPin size={18}/> {r.address}</h3><p><Clock size={18}/> {r.hours}</p><p>{r.email}</p><p className="notice">Illustrative venue only. The map points to the neighborhood, not a real restaurant.</p><a className="text-link" href={'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent('Bandra West Mumbai')} target="_blank" rel="noreferrer">Neighborhood directions <ArrowUpRight size={18}/></a>{key?<iframe title="Demo neighborhood map" loading="lazy" referrerPolicy="no-referrer-when-downgrade" src={'https://www.google.com/maps/embed/v1/place?key='+encodeURIComponent(key)+'&q=Bandra+West+Mumbai'}/>:<div className="map-placeholder"><MapPin size={34}/><h3>Bandra West, Mumbai</h3><p>Interactive map appears when a Google Maps Embed key is configured.</p></div>}</div><form className="stack" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;try{await api('/contact','POST',Object.fromEntries(new FormData(form)));notify('Message received. Our team will be in touch.');form.reset();}catch(e:any){notify(e.message);}}}><h3>A note to the kitchen.</h3><label>Your name<input name="name" required minLength={2}/></label><label>Email address<input name="email" type="email" required/></label><label>Your message<textarea name="message" rows={6} required minLength={10} maxLength={2000}/></label><button className="button primary">Send your message <ArrowUpRight size={18}/></button></form></div></section>;}
